services:
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   volumes:
  #     - ./zookeeper/data:/var/lib/zookeeper/data
  #     - ./zookeeper/datalog:/var/lib/zookeeper/log
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 2181:2181

  # kafka_1:
  #   image: confluentinc/cp-kafka:latest
  #   volumes:
  #     - ./kafka_1/data:/var/lib/kafka/data
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: INTERNAL://:19092,EXTERNAL://:9092
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_1:19092,EXTERNAL://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    # depends_on:
    #   - zookeeper
    ports:
      - 9095:9095
      - 19095:19095
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: 192.168.137.1:2181
      KAFKA_LISTENERS: INTERNAL://:19095,EXTERNAL://:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://192.168.137.225:19095,EXTERNAL://192.168.137.225:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 5
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 5
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 5
      KAFKA_MIN_INSYNC_REPLICAS: 5

  # kafka_3:
  #   image: confluentinc/cp-kafka:latest
  #   volumes:
  #     - ./kafka_3/data:/var/lib/kafka/data
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9094:9094
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: INTERNAL://:19094,EXTERNAL://:9094
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_3:19094,EXTERNAL://localhost:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3

  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     KAFKA_BROKERCONNECT: "kafka_2:19095"
  #   depends_on:
  #     - kafka_5
      
